name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: git@github.com:NTU-Dzoo/dzoo-docs.git
        TARGET_BRANCH: master
        BUILD_SCRIPT: cd docs && npm install && npm run build
        BUILD_DIR: .vuepress/dist
        CNAME: https://docs.dzoo.ntu.edu.tw
